name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Download Tesseract English model
        run: |
          mkdir -p app/src/main/assets/tessdata
          curl -L -o app/src/main/assets/tessdata/eng.traineddata             https://github.com/tesseract-ocr/tessdata_best/raw/main/eng.traineddata

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: WordsearchSolver-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
